branch-defaults:
  master:
    environment: null
  townhall_styling:
    environment: null
global:
  application_name: meatballs
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git
